[Service]
# USRP parameters
Environment=USRP_BIND=127.0.0.1
Environment=USRP_HOST=127.0.0.1
Environment=USRP_RXPORT=34011
Environment=USRP_TXPORT=32011
# Zello credentials
Environment=ZELLO_USERNAME=<Zello Username>
Environment=ZELLO_PASSWORD=<Zello Password>
Environment=ZELLO_CHANNEL="<Zello Channels>"
# Zello Free variables
Environment=ZELLO_PRIVATE_KEY=test.key
Environment=ZELLO_ISSUER=***
Environment=ZELLO_WS_ENDPOINT=wss://zello.io/ws
# Zello Work variables
#Environment=ZELLO_API_ENDPOINT=https://mynetwork.zellowork.com
#Environment=ZELLO_WS_ENDPOINT=wss://zellowork.io/ws/mynetwork
# Logging parameters
Environment=LOG_LEVEL=DEBUG
Environment=LOG_FORMAT="%(levelname)s:%(name)s:%(message)s"
Environment=LOG_DIR="/var/log/zello_bridge"
# Audio parameters
Environment=USRP_GAIN_RX_DB=0
Environment=USRP_GAIN_TX_DB=0